export const APP_LOAD_REQUEST = 'APP_LOAD_REQUEST';
export const APP_LOAD_RESOLVE = 'APP_LOAD_RESOLVE';
export const APP_LOAD_FAILURE = 'APP_LOAD_FAILURE';
export const APP_SAVE_REQUEST = 'APP_SAVE_REQUEST';
export const APP_SAVE_RESOLVE = 'APP_SAVE_RESOLVE';
export const APP_SAVE_FAILURE = 'APP_SAVE_FAILURE';
export const UPDATE_EDITOR_STATE = 'UPDATE_EDITOR_STATE';
export const TOGGLE_EDITOR_FOCUS = 'TOGGLE_EDITOR_FOCUS';
