export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESOLVE = 'LOGIN_RESOLVE';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_RESOLVE = 'SIGNUP_RESOLVE';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
